- name: apt update
  become: yes
  apt: update_cache=yes

- name: install linux-headers
  become: yes
  shell: apt-get install -y linux-headers-$(uname -r)

- name: git clone bcc
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/iovisor/bcc.git"
    dest: /home/{{ user }}/bcc

- name: mkdir bcc/build
  file: path=/home/{{ user }}/bcc/build state=directory owner="{{ user }}" group="{{ user }}" mode=0755

- name: cmake ..
  command: chdir=/home/{{ user }}/bcc/build cmake ..

- name: make
  command: chdir=/home/{{ user }}/bcc/build make

- name: sudo make install
  become: yes
  become_user: "{{ user }}"
  command: chdir=/home/{{ user }}/bcc/build sudo make install

- name: cmake -DPYTHON_CMD=python3 ..
  command: chdir=/home/{{ user }}/bcc/build cmake -DPYTHON_CMD=python3 ..

- name: make
  command: chdir=/home/{{ user }}/bcc/build/src/python make

- name: sudo make install
  become: yes
  become_user: "{{ user }}"
  command: chdir=/home/{{ user }}/bcc/build/src/python sudo make install
