- name: apt update
  become: yes
  apt: update_cache=yes

- name: git clone bpftrace
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/iovisor/bpftrace"
    dest: /home/{{ user }}/bpftrace

- name: mkdir bpftrace/build
  file: path=/home/{{ user }}/bpftrace/build state=directory owner="{{ user }}" group="{{ user }}" mode=0755

- name: cmake
  command: chdir=/home/{{ user }}/bpftrace/build cmake -DCMAKE_BUILD_TYPE=Release ..

- name: make
  command: chdir=/home/{{ user }}/bpftrace/build sudo make -j2

- name: make install
  become: yes
  become_user: "{{ user }}"
  command: chdir=/home/{{ user }}/bpftrace/build sudo make install
