- name: apt update
  become: yes
  apt: update_cache=yes

- name: apt install bpftrace
  become: yes
  apt:
    name: "{{ bpftrace_packages }}"
    state: latest

- name: git clone bpftrace
  git:
    repo: "https://github.com/iovisor/bpftrace"
    dest: /home/{{ user }}/

- name: mkdir bpftrace/build
  command: chdir=/home/{{ user }}/ mkdir bpftrace/build; 

- name: cmake
  command: chdir=/home/{{ user }}/bpftrace/build cmake -DCMAKE_BUILD_TYPE=Release ..

- name: make
  command: chdir=/home/{{ user }}/bpftrace/build make -j8 

- name: make install
  become: yes
  become_user: "{{ user }}"
  command: chdir=/home/{{ user }}/bpftrace/build sudo make install
