- name: apt update
  apt: update_cache=yes

- name: install packages
  apt: 
    name: "{{ pre_packages }}"
    state: latest

- name: install bpf_compile_tools
  become: yes
  apt:
    name: "{{ bpf_compile_packages }}"
    state: latest

- name: install bpftrace_packages
  become: yes
  apt:
    name: "{{ bpftrace_packages }}"
    state: latest

- name: install bcc_packages
  become: yes
  apt:
    name: "{{ bcc_packages }}"
    state: latest
